### ISSUE TITLE
File to flash

### ISSUE THREAD

**Issue by juanka99** [odig/eboxToMqtt#1]
I would like to test your application but I am not sure which file is the one to be flashed in the ESP32 in order to start configuring it.
Thanks.

**Comment by odig** [comment]
Hi, 
you have to checkout the Project and build it with VS-Code  and PlatformIO by yourself.
PlatfomIO is able to flash the ESP-32 on your behalf after compiling.

After compiling and flashin the ESP-32 will act as an AP and provides a config web site.

Hope that helps
 Ciao odig

**Comment by juanka99** [comment]
> Hi, you have to checkout the Project and build it with VS-Code and PlatformIO by yourself. PlatfomIO is able to flash the ESP-32 on your behalf after compiling.
> 
> After compiling and flashin the ESP-32 will act as an AP and provides a config web site.
> 
> Hope that helps Ciao odig

I'm going to search information about this and I´ll try... Thanks!
