### ISSUE TITLE
MQTT in Home Assistant

### ISSUE THREAD

**Issue by juanka99** [odig/eboxToMqtt#2]
I have flashed the ESP32 and this is the captive portal:
![image](https://user-images.githubusercontent.com/32193776/214126933-868ec165-b4b8-45ff-8f2e-3803b0965914.png)

No sensors appairs in Home Assistant mqtt... What I have to do?

**Comment by odig** [comment]
Can you telnet to 192.168.1.223 from you computer?
   telnet 192.168.1.223
Put in "help" and get an answer?

Check if infos are written to MQTT.
Use a tool like MQTTExplorer.
If you connect to your MQTT server (192.168.1.82) you should see entries on top level named "pytes".
There must be also a top level Entry named "homeassistant" for HA auto discovery.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/25546672/214137005-63a07281-4e14-46b4-822a-cffee912abad.png">

In HA there must be the integration "MQTT" installed.
This integration has an auto discovery feature which looks in "homeassistant" in MQTT.

**Comment by odig** [comment]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/25546672/214138291-6b3fa0ce-e2ec-4c8d-81cb-a06cabeeeeb4.png">

**Comment by juanka99** [comment]
![image](https://user-images.githubusercontent.com/32193776/214142107-da019117-46fa-4f9e-9698-001ee2772d0e.png)


![image](https://user-images.githubusercontent.com/32193776/214142403-66498c66-24fd-4d82-b46a-70a7f37e1e09.png)

**Comment by juanka99** [comment]
Is it mandatory to have the RS232 adapter connected for the mqtt connection to work?
I only have the ESP32. I haven't received the RS232 adapter yet...

**Comment by odig** [comment]
Without an RS232 adapter you don't get entities but the error Message should not show up if MQTT server is available and properly configured.

Looks like your MQTT IP or USER or PASSWORD is not correct.

Normally Homeassitant IP and an Homeassistant User and his Password.
And you have "Mosquito Broker" installed as an agent in Homeassistant.

**Comment by juanka99** [comment]
> Without an RS232 adapter you don't get entities but the error Message should not show up if MQTT server is available and properly configured.
> 
> Looks like your MQTT IP USER or PASSWORD is not correct.
> 
> Normally Homeassitant IP and an Homeassistant User and his Password. And you have "Mosquito Broker" installed as an agent in Homeassitant.

IP, USER and PASSWORD are correct. The same I use in MQTT Explorer:

![image](https://user-images.githubusercontent.com/32193776/214144005-6260ce34-bbdd-4a97-ba49-9bb256e83212.png)

**Comment by odig** [comment]
If MQTT explorer works, the ESP32 should also.

Double check user and pasword please.

Looks like all is on the same network (192.168.1.x).
MQTT uses a normal TCP/IP connection on port 1883 on default.
Can you ping/telnet the ESP32 from homeassistant console?

If you remove the comment from line 1 in src/main.cpp you enable SIMULATION and no serial is needed.

**Comment by juanka99** [comment]
> If MQTT explorer works, the ESP32 should also.
> 
> Double check user and pasword please.
> 
> Looks like all is on the same network (192.168.1.x). MQTT uses a normal TCP/IP connection on port 1883 on default. Can you ping/telnet the ESP32 from homeassistant console?
> 
> If you remove the comment from line 1 in src/main.cpp you enable SIMULATION and no serial is needed.

I have check 3 times user and password. And I ping the ESP32 from Homeassistant without problem:

![image](https://user-images.githubusercontent.com/32193776/214147451-80c16093-65ed-44aa-932f-78181d47ba34.png)

**Comment by juanka99** [comment]
Hi again,

My ESP32 is like this. Could be this the problem? 

![image](https://user-images.githubusercontent.com/32193776/214226686-67ae0404-9866-40b9-b677-514bc01d6d89.png)


Or the mqttServer IP? 

![image](https://user-images.githubusercontent.com/32193776/214228325-e2de031d-81f9-4a2b-8719-1be02304252f.png)

**Comment by odig** [comment]
You are right,
I was totally out of my mind coding the mqttServer config.

Please adjust line 78 for now for your needs.
I'll will fix the code these days.

**Comment by juanka99** [comment]
> You are right, I was totally out of my mind coding the mqttServer config.
> 
> Please adjust line 78 for now for your needs. I'll will fix the code these days.

Ok. 
I'll do it this afternoon when I get home. I'll let you know how the change has gone.

**Comment by juanka99** [comment]
> You are right, I was totally out of my mind coding the mqttServer config.
> 
> Please adjust line 78 for now for your needs. I'll will fix the code these days.

I adjust line 78 with
IPAddress mqttServer(192, 168, 1, 82);
and all it´s same. It doesn´t work

![image](https://user-images.githubusercontent.com/32193776/214326241-d5b94930-f889-496e-8cf4-8dec9a0937e6.png)

**Comment by juanka99** [comment]
Is there anything else I have to edit to make it work? 

I'm about to give up :-(

**Comment by odig** [comment]
Please change line 766 to your user and password.
As i said forgot to use the configured values for MQTT. Sorry.

Otherwise there should be time on weekend to fix and debug it myself.

**Comment by juanka99** [comment]
> Please change line 766 to your user and password. As i said forgot to use the configured values for MQTT. Sorry.
> 
> Otherwise there should be time on weekend to fix and debug it myself.

Are these user and password respectively?

![image](https://user-images.githubusercontent.com/32193776/214334805-003498bc-d1ba-40b5-a8a5-df8ef5c15c3e.png)

**Comment by juanka99** [comment]
> Please change line 766 to your user and password. As i said forgot to use the configured values for MQTT. Sorry.
> 
> Otherwise there should be time on weekend to fix and debug it myself.

Line changed and now this is MQTT Explorer test: 

![image](https://user-images.githubusercontent.com/32193776/214338069-4231d4f8-e3b1-45cb-b939-2655101c3bc2.png)

**Comment by odig** [comment]
MQTT is now connected. :-)

If you wanna see simulated data as long you have no serial connected remove the "//" in line 1 to define SIMULATION

**Comment by juanka99** [comment]
> MQTT is now connected. :-)
> 
> If you wanna see simulated data as long you have no serial connected remove the "//" in line 1 to define SIMULATION

Done! 

Only this:  

![image](https://user-images.githubusercontent.com/32193776/214342757-73ee0f1f-158f-4886-b3dd-a79edc7222a8.png)

**Comment by odig** [comment]
You have to connect RX and TX via wire on the ESP32 for SIMULATION to work.
Or wait for your level shifter.
Simulation writes to pytes2 instead of pytes.
And auto discover to pytes2_discover instead of homeassistant.

**Comment by juanka99** [comment]
> You have to connect RX and TX via wire on the ESP32 for SIMULATION to work. Or wait for your level shifter. Simulation writes to pytes2 instead of pytes. And auto discover to pytes2_discover instead of homeassistant.

RX and TX connected via wire, but no new entities in homeassistant:

![image](https://user-images.githubusercontent.com/32193776/214441616-79c36b21-562b-4343-bd1c-43ca0a74b876.png)

**Comment by odig** [comment]
I need more info of your background.
Are you new to HA and MQTT?

Homeassistant is mostly plug and play but you need to know some basics.
The MQTT integration in Homeassistant (HA) looks in the "homeassistant" topic in MQTT for autodiscovery.
The simulation intentionally writes to "pytes2_discover" instead of "homeassistant" otherwise tye entities will show up in your HA and need to get rid of them in your history afterwards.
If you want to see them in your HA change the string "pytes2_discover" to "homeassistant".

The simulation was intented for me to see if the MQTT topics are filled in correct and the communication works.

MQTT is an universal tool. If you don't to use HA you can easily use any other home atomation system subscribing to the pytes(2) topics "pytes2/bat/1/volt" for example like NodeRed.

You have to get the whole picture.
eboxToMqtt -> MQTT (topics: "homeassistant" for autodiscovery and "pytes" for values) -> homeassitant: MQTT integration

**Comment by juanka99** [comment]
Hi again!

I have received the level shifter, I have connected it to the ESP32 and the Pytes, and the entities still do not appear in HA. I think there must be some other parameter in the configuration that needs to be changed and you don't remember it... Could this be?

![image](https://user-images.githubusercontent.com/32193776/214617809-0cae3291-07dc-4825-8e2a-aa4f81a8b535.png)

**Comment by odig** [comment]
It is important to check the whole dataflow

## 1. Disable Simulation
Put the "//" back in before line 1 SIMULATION.
build and reflash the ESP32.

Delete PYTES2 stuff in MQTT explorer

## 2. Is there a communication to the battery pack
check with telnet if you get an answer on "help" comand from PYTES.
If not: RX and TX has to be swapped.

## 3. Are the needed MQTT topics available
You should have an pytes topic in MQTT with actual values "pytes/bat/1/1/volt".
There should be an homeassistant topic in MQTT "homeassistant/sensor/pytes_bat_1_1/volt/config".

containing:

`{
  "name": "pytes_bat_1_1_volt",
  "unique_id": "pytes/bat/1/1/volt",
  "state_topic": "pytes/bat/1/1/volt",
  "device_class": "voltage",
  "state_class": "measurement",
  "qos": 0,
  "unit_of_measurement": "V",
  "value_template": "{{ value_json.value }}",
  "availability_mode": "all",
  "device": {
    "identifiers": [
      "pytes/bat/1/1/volt"
    ],
    "name": "pytes bat1 1 (volt)",
    "sw_version": ""
  }
}`

## 3. Add and configure MQTT integration in HA:
You need to have the MQTT intergration added in HA:

![image](https://user-images.githubusercontent.com/25546672/214630276-ad719209-3c2c-42a4-8dd0-3bbca30d767d.png)
![image](https://user-images.githubusercontent.com/25546672/214632341-9450f14c-c40f-403e-b0a3-322aa61bc768.png)

## 4. Entitys should showing up in HA
:-)

**Comment by juanka99** [comment]
1. SIMULATION was already disabled

2. Could you tell me exactly what command I have to use to know if there is communication with the batteries?

3. No homeassistant topic appears. Only the one in the following image:

![image](https://user-images.githubusercontent.com/32193776/214645485-f3b8a88c-b9de-4e4e-9f4f-ca18e58498b2.png)


4. MQTT integration already had it up and running in HA, and entities don't show up in HA

I don't know what else  :to try anymore. I am totally heartbroken :-((

**Comment by odig** [comment]
Before you can go further Step 2 has to function.
Otherwise no data will be filled in MQTT and due to this there are no entitys in HA.

## Things to test
- Putty/Telnet to 192.168.1.223 (your esp32)
- type in the command "help" and press ENTER
- you should get:

![image](https://user-images.githubusercontent.com/25546672/214649441-9dd04f40-7a02-49f1-b007-2918053b65f8.png)

This is the help direct from your battery's.

If this doesn't work the Serial connection is not established.


## Possible causes:
- RX/TX cables switched
- Wrong PINs used on your ESP32
- Connection Problems
- Wrong Layout on western jack
- Wrong port used on your battery (Console is the right one)
...

**Comment by odig** [comment]
I checked your ESP32 photo.
You used the wrong pins.
You have to use the serial Interface on the ESP32.
On your ESP32 Board it is on the pins marked RXD and TXD not G16 and G17.

https://medesign.seas.upenn.edu/uploads/Guides/NodeMCUPinout.png

If it doesn't work just switch the RX and TX Cable and give it a try.

Try put in "help" as command in telnet and press ENTER.
 If you get help youre nearly done.
 I'll bet the is the last problem.
If "help" worked and no entities showing up please show the content of "homeassistant" in MQTT explorer.

**Comment by juanka99** [comment]
A doubt: 

> I checked your ESP32 photo. You used the wrong pins. You have to use the serial Interface on the ESP32. On your ESP32 Board it is on the pins marked RXD and TXD not G16 and G17.
> 
> https://medesign.seas.upenn.edu/uploads/Guides/NodeMCUPinout.png
> 
> If it doesn't work just switch the RX and TX Cable and give it a try.
> 
> Try put in "help" as command in telnet and press ENTER. If you get help youre nearly done. I'll bet the is the last problem. If "help" worked and no entities showing up please show the content of "homeassistant" in MQTT explorer.

Any change here?

![image](https://user-images.githubusercontent.com/32193776/214677321-f2d376f7-0d0e-422d-be2d-475794c69952.png)

**Comment by odig** [comment]
Sorry i also have mixed up things.
G16 and G17 on you board is correct!
If "help" doesn't work just try connecting them the other way round.

Can you send detailed photos of ESP32, level shifter, western connector and your pytes front panel?

**Comment by juanka99** [comment]
> Sorry i also have mixed up things. G16 and G17 on you board is correct! If "help" doesn't work just try connecting them the other way round.
> 
> Can you send detailed photos of ESP32, level shifter, western connector and your pytes front panel?

All tests done. Everything remains the same. The "help" command still doesn't work.
![IMG_3298](https://user-images.githubusercontent.com/32193776/214688828-be06d56d-6339-49ce-b5ed-91c0d534cab9.jpg)
![IMG_3299](https://user-images.githubusercontent.com/32193776/214688839-44ae0f25-9014-43e8-88dd-5548fcd3972e.jpg)
![IMG_3300](https://user-images.githubusercontent.com/32193776/214688843-b145e5ed-9110-4a60-9ef4-5e1d176fd0ee.jpg)
![IMG_3301](https://user-images.githubusercontent.com/32193776/214688847-421fd124-b77d-4e85-8fb3-7ebaccd0978a.jpg)
![IMG_3302](https://user-images.githubusercontent.com/32193776/214689070-716898f6-4734-4cc5-ad4c-9a5826d50640.jpg)

**Comment by odig** [comment]
I rechecked the serial pins with your kind of ESP32 board these are correct (G16 and G17).

The last thing i see, is Green and Green/White are the other way round on my connection on the level shifter and Yellow and Green are the other way round.

so:
16/green on txd on ttl side of level shifter
17/yellow on rxd on ttl side of level shifter

green on txd on rs232 side of level shifter
green/white on rxd on rs232 side of level shifter

![image](https://raw.githubusercontent.com/odig/eboxToMqtt/main/pics/esp32.jpeg)
![image](https://raw.githubusercontent.com/odig/eboxToMqtt/main/pics/level_shifter.jpeg)
![image](https://raw.githubusercontent.com/odig/eboxToMqtt/main/pics/rj45.jpeg)

**Comment by juanka99** [comment]
Working!!!

![image](https://user-images.githubusercontent.com/32193776/214701979-c6ffce0d-1b11-4ec3-84f6-a4f3df914b47.png)


Here was the problem: 

![image](https://user-images.githubusercontent.com/32193776/214702132-b324c006-67fe-4c8b-a0a6-86ceae76c389.png)


Thank you for all!!!

**Comment by odig** [comment]
Yeah !!!
Congrats to try so hard.

**Comment by juanka99** [comment]
Job finished!

![photo_2023-01-26_16-55-45](https://user-images.githubusercontent.com/32193776/214885576-353b395b-9523-4499-9aeb-7429f6e0bfef.jpg)




https://user-images.githubusercontent.com/32193776/214886923-ba49d65f-9316-4bef-a138-e3ff3c1f2a65.mp4

**Comment by odig** [comment]
MQTT config is fixed
