### ISSUE TITLE
Readings stay frozen in HA

### ISSUE THREAD

**Issue by juanka99** [odig/eboxToMqtt#3]
Good morning!

It has hung up several times and I had to turn it off and on to get it to work again... has it happened to you? 

Thaks!

**Comment by juanka99** [comment]
@odig , is this normal?

**Comment by odig** [comment]
No,
but i have a guess that sometimes the WLAN login runs in a timeout and changes to config mode.
I increased the timeout.
And fixed the MQTT config.

If you lost connection again please check if the config WLAN is available.
