### ISSUE TITLE
New platformio.ini doesn't work

### ISSUE THREAD

**Issue by juanka99** [odig/eboxToMqtt#4]
Hi,
I saw you changed platformio.ini a few hours ago but I think there is a problem. It's incomplete.
You could review it?
Thanks

**Comment by odig** [comment]
I reverted the serial config I changed

**Comment by juanka99** [comment]
> I reverted the serial config I changed

Only 36 lines???

![image](https://user-images.githubusercontent.com/32193776/219142326-400d85a3-9351-42ff-8d0d-7d6173a42f42.png)

**Comment by juanka99** [comment]
I can't get the access point PYTES-E-BOX-48100-R to activate

**Comment by odig** [comment]
Yes, you can see the changes on GitHub.
Click on the file and than “history” in the upper right corner

The file format was change from CRLF line endings to LF please try again.

**Comment by odig** [comment]
If it is already configured it should startup normal in your WIFI and can be accessed via you're network IP.
It falls back to PYTES-E-BOX-48100-R only if it is not reachable for 5 minutes now (was 10sec in old version).
So you don't have to reconfigure on a new software version.

**Comment by odig** [comment]
Works on my side
